### PR TITLE
Fix #118 (sort of)

### LINKED ISSUE #118: Error when trying to download a Snapshot version from nexus
When trying to download a snapshot version from nexus there seems to be a file naming problem. For example, when I try and download library 1.1-SNAPSHOT it does download it but it saves the file using the snapshot timestamp format.

```
/tmp/kitchen/cache/artifact_deploys/library/1.1-SNAPSHOT/library-1.1-20140210.180346-6.tar.gz
```

This causes artifact problems and generates this error.

```
Errno::ENOENT: artifact_deploy[library] (library::default line 43) had an error: 
Errno::ENOENT: artifact_file[/tmp/kitchen/cache/artifact_deploys/library/1.1-SNAPSHOT/library-1.1-SNAPSHOT.tar.gz] (library::none line 582) had an error: 
Errno::ENOENT: No such file or directory - /tmp/kitchen/cache/artifact_deploys/library/1.1-SNAPSHOT/library-1.1-SNAPSHOT.tar.gz
```

Is there a way to resolve that?

### PR DESCRIPTION
**Pull request by gregsymons**
This pull should fix the artifact_deploy use case for SNAPSHOT versions. I'm
not entirely certain that it fixes artifact_package or artifact_file; in fact
I'm fairly certain that artifact_file still has some bugs around SNAPSHOTS.
However, this fixes _my_ use case, so that's good enough for me :smile:

### CODE REVIEW

**Comment by KAllan357** [comment]
I'm not sure how this fixes the issue. Wouldn't this still return a string of `"1.0.0-SNAPSHOT"`?

**Comment by gregsymons** [comment]
For snapshot builds, the `<version>` tag is the timestamped version; the `<baseVersion>` tag contains `"1.0.0-SNAPSHOT"`.

**Comment by KAllan357** [comment]
Thanks. I understand now how this will work. Let me add a few comments, but overall this seems like it will fit nicely.

File: libraries/chef_artifact_nexus.rb [hunk 1]
```diff
@@ -28,7 +28,7 @@ def remote
       # @return [String] the version number that latest resolves to or the passed in value
       def get_actual_version(coordinates)
         artifact = NexusCli::Artifact.new(coordinates)
-        if Chef::Artifact.latest?(artifact.version)
+        if Chef::Artifact.latest?(artifact.version) or Chef::Artifact.snapshot?(artifact.version)
```
Comment (KAllan357) [inline libraries/chef_artifact_nexus.rb]: I'd prefer `||` here over the `or`

File: metadata.rb [hunk 2]
```diff
@@ -3,7 +3,7 @@
 maintainer_email "kallan@riotgames.com"
 license          "Apache 2.0"
 description      "Provides your cookbooks with the Artifact Deploy LWRP"
-version          "1.11.3"
+version          "1.11.4"
```
Comment (KAllan357) [inline metadata.rb]: If you could please revert this, I will take care of this step when we release.

**Comment by gregsymons** [comment]
Both comments are addressed as of @4e43b9c

File: libraries/chef_artifact.rb [hunk 3]
```diff
@@ -200,6 +200,17 @@ def latest?(version)
...
 
+      # Convenience metho for determining whether a version is a snapshot
+      # version.
+      #
+      # @param version [String] the version of the configured artifact to check
+      #
+      # @return [Boolean] true if the version ends with "-SNAPSHOT" (case
+      # sensitive)
+      def snapshot?(version)
+        version.end_with?("-SNAPSHOT")
```
Comment (capoferro) [inline libraries/chef_artifact.rb:211]: Perhaps we should allow this to be overridden with an attribute specifying a regex.

For example, some people, instead of using `1.0.2-SNAPSHOT` will use `1.0.2.sha.5114f85` to specify which commit hash the snapshot is built from. In that case, the cookbook writer would override an attribute (for example `node['artifact']['snapshot_regex']`) to be `"\.sha\.[a-z0-9]+$"`.

This code could look like this instead:

``` ruby
# artifact-cookbook/attributes/default.rb
default['artifact']['snapshot_regex'] = "-SNAPSHOT$"
```

``` ruby
# artifact-cookbook/libraries/chef_artifact.rb
def snapshot?(version)
  !!version.match(/#{node['artifact']['snapshot_regex']}/)
end
```

This would also address the case where the snapshot segment of a version is not at the end of the version. The custom regex could match any part of the string.

The above example defaults to matching `-SNAPSHOT` at the end of the string, just the same as you have implemented here.

Comment (capoferro) [inline libraries/chef_artifact.rb:211]: Tho this might be overcomplicating as we don't need that functionality yet as this is intended only to be used for mvn stuffs.  If it is only for mvn, I'd recommend moving this functionality into Chef::Artifact::Nexus to indicate the intent.

**Comment by KAllan357** [comment]
@gregsymons This looks good. Thank you for the contribution! I think there are some places this same code could fit in order to fix up the `artifact_file` / `artifact_package` resources.
