### PR TITLE
Pass the environment around, instead of the node

### LINKED ISSUE #97: Undefined method 'chef_environment' (looks like from chef_artifact_nexus_configuration library)
I just upgraded to 1.10.0, however every time I run chef-client it fails.

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/artifact/resources/deploy.rb
================================================================================


NoMethodError
-------------
undefined method `chef_environment' for nil:NilClass


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/artifact/libraries/chef_artifact.rb:235:in `encrypted_data_bag_for'
  /var/chef/cache/cookbooks/artifact/libraries/chef_artifact.rb:71:in `data_bag_config_for'
  /var/chef/cache/cookbooks/artifact/libraries/chef_artifact_nexus_configuration.rb:6:in `from_data_bag'
  /var/chef/cache/cookbooks/artifact/resources/deploy.rb:56:in `class_from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/artifact/libraries/chef_artifact.rb:

228:        # @return [Chef::Mash] the data bag item in Mash form
229:        def encrypted_data_bag_for(node, data_bag)
230:          @encrypted_data_bags = {} unless @encrypted_data_bags
231:
232:          if encrypted_data_bags[data_bag]
233:            return get_from_data_bags_cache(data_bag)
234:          else
235>>           data_bag_item = encrypted_data_bag_item(data_bag, node.chef_environment)
236:            data_bag_item ||= encrypted_data_bag_item(data_bag, WILDCARD_DATABAG_ITEM)
237:            data_bag_item ||= encrypted_data_bag_item(data_bag, "nexus")
238:            data_bag_item ||= {}
239:            @encrypted_data_bags[data_bag] = data_bag_item
240:            return data_bag_item
241:          end
242:        end
243:
244:        # @return [Hash]
```

Looking in the code (https://github.com/RiotGames/artifact-cookbook/blob/master/libraries/chef_artifact_nexus_configuration.rb#L6), nil is being passed in for the node object which then tries to call chef_environment on it.

This might be a different code-path as I am using the S3 deploy method in a Vagrant box (so with an encrypted data_bag, running against chef-server).

If this is just specific to the S3 case, perhaps I should convert the configuration to follow the same model as the new Nexus config?  Going back to a commit before the chef_artifact_nexus_configuration was added fixes it for me.

### PR DESCRIPTION
**Pull request by KAllan357**
Should fix #97

### CODE REVIEW

File: libraries/chef_artifact_nexus_configuration.rb [hunk 1]
```diff
@@ -3,7 +3,13 @@ module Artifact
     class NexusConfiguration
       class << self
         def from_data_bag
-          config = Chef::Artifact.data_bag_config_for(nil, Chef::Artifact::DATA_BAG_NEXUS)
+          environment = unless Chef::Config[:solo]
+            Chef::Node.load(Chef::Config[:node_name]).chef_environment
```
Comment (KAllan357) [inline libraries/chef_artifact_nexus_configuration.rb:7]: I'm not entirely sure how I feel about this here. It means an extra REST call to the Chef server. On the other hand, you are never guaranteed that `Chef::Config[:environment]` will be set on your `client.rb` and the node is not available in Library code, so there might not be another way to do this.

**Comment by ivey** [comment]
:+1: until chef allows passing node data into lwrps
